### ISSUE TITLE
Publishing jar to maven server

### ISSUE THREAD

**Issue by harmandeeps** [ishugaliy/allgood-consistent-hash#6]
Hi Ishugaliy

We have been trying to use this library in our project. Locally, one can setup github configs to pull in jars from github packages, but still everyone has to do this setup manually. If possible, Can you please publish the jar on maven server? It will really help to use this library easily. 

Thanks.

**Comment by ishugaliy** [comment]
Hi, @harmandeeps 

Indeed, GitHub is not a really convenient way to store packages.
Will release it to the maven server in a close time.

Thanks for the feedback

**Comment by harmandeeps** [comment]
@ishugaliy : Thank you for the prompt reply. If possible, Can you please tell us any tentative time?

**Comment by ishugaliy** [comment]
@harmandeeps I have released it to the maven central

You can find it [here](https://search.maven.org/artifact/com.github.ishugaliy/allgood-consistent-hash/1.0.0/jar):
```
<dependency>
  <groupId>com.github.ishugaliy</groupId>
  <artifactId>allgood-consistent-hash</artifactId>
  <version>1.0.0</version>
</dependency>
```

I Will update library docs in the next few days.

@harmandeeps please, let me know if everything is okay or just close this issue if so.

Thanks

**Comment by harmandeeps** [comment]
Thank you @ishugaliy for fixing this quickly. I checked it is working fine, closing the issue.
